### PR TITLE
Be consistent in our testing environment

### PR DESCRIPTION
**Pull request by SeanTAllen**
We want to make sure that:

- All releases are done in an environment that has been tested by
- Doing nightly releases that run in an environment that has been tested by
- Testing for CI

For changelog-tool that means the shared docker x86 linux builder
image which has `release` and `latest` versions that correspond to
latest ponyc versions.

### CODE REVIEW

**Comment by SeanTAllen** [comment]
The current failure is good. It has exposed something I saw in one test last night when we had a less consistent testing platform. I need to track down how stable is triggering an illegal instruction.

**Comment by SeanTAllen** [comment]
What's really weird is that `ponyup` also uses stable but doesn't get an illegal instruction and as far as I know, it's the same `stable`.

My guess is that it isn't the same stable.

**Comment by SeanTAllen** [comment]
I think I see the issue. In the ponyc Alpine image, we build stable in an arch dependent fashion which could end up being very bad. That will be fixed with the next release image. For now, I am going to work around in the base shared builder image and see if that is corrected.

**Comment by SeanTAllen** [comment]
I fixed the issue temporarily in the based shared docker builder. We should be good until this gets fixed in general when we switch release ponyc images to using artifacts from Cloudsmith via ponyup.

**Review by EpicEric — APPROVED** [review]

**Pull request merged**
